<a href="https://colab.research.google.com/github/AlvisSu/20220702-python-lesson/blob/main/20220723.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 複習一下套件載入慣用法

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

# Numpy
* ndarray
* ufunc

## ndarray
* indexing
* slicing

In [1]:
import numpy as np

In [3]:
data = np.arange(25)

In [4]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
data*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

## 檢查ndarray的屬性

In [9]:
data.dtype?

In [6]:
data.dtype

dtype('int64')

In [7]:
data.size

25

In [8]:
data.shape

(25,)

## 改變ndarray的形狀

In [10]:
data.reshape?

In [12]:
#reshape不會改變原本的值
data.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#overwrite original data
data = data.reshape(5,5)