<a href="https://colab.research.google.com/github/AlvisSu/20220702-python-lesson/blob/main/20220730.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 使用Teachable Machine

In [5]:
#解壓縮
!unzip model.zip

Archive:  model.zip
replace keras_model.h5? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [29]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('keras_model.h5')

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('00725.jpg')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)

[[0.96174896 0.03825106]]


# 使用Gradio打包上面的模型來使用

In [ ]:
!pip install gradio

In [17]:
import random

In [26]:
def classify(image):
  # Load the model
  model = load_model('keras_model.h5')

  image.save(f"{random.randint(0, 10000):05}.jpg")

  # Create the array of the right shape to feed into the keras model
  # The 'length' or number of images you can put into the array is
  # determined by the first position in the shape tuple, in this case 1.
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  # Replace this with the path to your image
  # image = Image.open('AS.png')
  #resize the image to a 224x224 with the same strategy as in TM2:
  #resizing the image to be at least 224x224 and then cropping from the center
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.ANTIALIAS)

  #turn the image into a numpy array
  image_array = np.asarray(image)
  # Normalize the image
  normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
  # Load the image into the array
  data[0] = normalized_image_array

  # run the inference
  prediction = model.predict(data)
  labels = ["戴著口罩的A", "沒有戴口罩的A"]
  return labels[np.argmax(prediction)]

In [27]:
import gradio as gr

In [28]:
gr.Interface(classify, inputs=gr.Image(type="pil"), outputs="text").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://34142.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x7f49fbaf2710>,
 'http://127.0.0.1:7863/',
 'https://34142.gradio.app')

In [21]:
from PIL import Image

In [22]:
im = Image.open("05553.jpg")

In [25]:
classify(im)

'戴著口罩的A'

In [32]:
x = [1, 2, 3, 4, 3, 2, 1]

In [33]:
#讓y最大的x值
#y=f(x)
np.argmax(x)

3

## 練習

請輸出0-15的二進位及時溜進位的數值

In [45]:
#i:2>>保持兩位數，i:02>>兩位數+0
for i in range(16):
  print(f"{i:2}的二進位是:{i:b}")

 0的二進位是:0
 1的二進位是:1
 2的二進位是:10
 3的二進位是:11
 4的二進位是:100
 5的二進位是:101
 6的二進位是:110
 7的二進位是:111
 8的二進位是:1000
 9的二進位是:1001
10的二進位是:1010
11的二進位是:1011
12的二進位是:1100
13的二進位是:1101
14的二進位是:1110
15的二進位是:1111


In [46]:
#對齊、補0
for i in range(16):
  print(f"{i:2}的二進位是:{i:04b}")

 0的二進位是:0000
 1的二進位是:0001
 2的二進位是:0010
 3的二進位是:0011
 4的二進位是:0100
 5的二進位是:0101
 6的二進位是:0110
 7的二進位是:0111
 8的二進位是:1000
 9的二進位是:1001
10的二進位是:1010
11的二進位是:1011
12的二進位是:1100
13的二進位是:1101
14的二進位是:1110
15的二進位是:1111


# Scikit-Learn 簡介

```python
1.載入模型

from sklearn.svm import SVC

2.建立模型

clf = SVC()

3.訓練模型

clf.fit(x_train, y_train)

4.使用模型

y_predict = clf.predict(x_test)
```

## 載入資料集

In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
X = iris.data

In [21]:
y = iris.target

In [27]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [28]:
len(X)

150

In [24]:
y[0]

0

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 拆分訓練集及測試集

X:題目

Y:答案

In [18]:
from sklearn.model_selection import train_test_split

In [35]:
#網站抓取原資料
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [36]:
#20%拿來做測試
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 使用SVM來做分類

In [37]:
#1. 載入模型
from sklearn.svm import SVC

In [38]:
#2. 建立模型
clf = SVC()

In [39]:
#3. 訓練模型
clf.fit(X_train, y_train)

SVC()

In [40]:
# 計算模型準確度(Accuracy)
clf.score(X_test, y_test)

1.0

In [41]:
#4. 使用模型
clf.predict(X_test)

array([2, 1, 0, 2, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 0, 0, 2, 1, 2, 0, 2, 0,
       1, 1, 0, 1, 1, 0, 1, 0])

## 使用Random Forest來做分類

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [42]:
#1. 載入模型
from sklearn.ensemble import RandomForestClassifier

In [43]:
#2. 建立模型
#clf = RandomForestClassifier(max_depth=2, random_state=0)
#clf = RandomForestClassifier() << 使用預設
clf = RandomForestClassifier()

In [48]:
#3. 訓練模型
clf.fit(X_train, y_train)

RandomForestClassifier()

In [49]:
# 計算模型準確度(Accuracy)
clf.score(X_test, y_test)

1.0

In [50]:
#4. 使用模型
clf.predict(X_test)

array([2, 1, 0, 2, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 0, 0, 2, 1, 2, 0, 2, 0,
       1, 1, 0, 1, 1, 0, 1, 0])

### 太多資訊over fitting